### ISSUE TITLE
Cannot reproduce code execution of the LanguageDetection sample

### ISSUE THREAD

**Issue by joslat** [curiosity-ai/catalyst#55]
**Describe the bug**
Referencing the latest NuGet package, Catalyst 1.0.16767, and essentially putting the code of the sample for Language Detection, throws an exception.
The exception: {"Unable to load one or more of the requested types.\r\nA ByRef-like type cannot be used as the type for an instance field in a non-ByRef-like type."}

my code is as follows:
![image](https://user-images.githubusercontent.com/9831011/119678643-fa826a00-be3f-11eb-8f9c-df762b224a4a.png)

Essentially the same as the sample, but I have tried the sample locally, updated the package to match, and it works...
I am also using .NET 5, the same as the sample.

The sensible part of the stacktrace is:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Mosaik.Core.ObjectStore.<>c.<CreateDerivedFromModelDictionary>b__28_1(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.UnionIterator`1.FillSet()
   at System.Linq.Enumerable.UnionIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Mosaik.Core.ObjectStore.CreateDerivedFromModelDictionary()
   at Mosaik.Core.ObjectStore.<>c.<.cctor>b__32_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Mosaik.Core.ObjectStore.TryGetFormerNames(String name, String[]& formerNames)
   at Catalyst.Models.FastText.<GetMatrixStreamsAsync>d__42.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Catalyst.Models.FastText.<FromStoreAsync_Internal>d__41.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Catalyst.Models.FastTextLanguageDetector.<FromStoreAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

Could it be an issue with getting the Language files from the store? if so, how is detailed how to do this?

**To Reproduce**
Create a new project, add reference to Catalyst, paste the code and run. 

**Expected behavior**
runs flawlessly, language is returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/9831011/119678643-fa826a00-be3f-11eb-8f9c-df762b224a4a.png)

**Additional context**
_Add any other context about the problem here._

**Comment by joslat** [comment]
To help a bit more, I debugged with "just my code " off, and...

The issue seems to happen here:
![image](https://user-images.githubusercontent.com/9831011/119955527-6aa80180-bfa0-11eb-9717-fcd18bfd5fd9.png)

Then, on the Lazy initialization of that value, we get the exception:
![image](https://user-images.githubusercontent.com/9831011/119956405-5d3f4700-bfa1-11eb-94e6-8cd6be1b1180.png)

**Comment by theolivenbaum** [comment]
Hi @joslat , are you still seeing this issue?
